version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:  
          command:
            docker run -d -t --name buildkite-agent buildkite/agent:3 start --token "a16a145c88deddf524006982f85743f60e4e8663ef34a4bde2" buildkite/agent
      - run:  
          command:
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198
      - run:  
          command:
            sudo apt-get update && sudo apt-get install -y buildkite-agent
      - run:  
          command:
            sudo sed -i "s/xxx/a16a145c88deddf524006982f85743f60e4e8663ef34a4bde2/g" /etc/buildkite-agent/buildkite-agent.cfg
      - run:  
          command:
            sudo service buildkite-agent start
            
            
            
            
            
            
            

